name: "Keep It Simple and Stupid"
description:

url:
author: "He Gu"
email: "gh1z114@gmail.com"
baseurl: ""
permalink: /:year/:month/:day/:title/
linenos: true

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
    input:          GFM
    # https://github.com/jekyll/jekyll/pull/4090
    syntax_highlighter: rouge

    # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
    # span, block element options fall back to global
    syntax_highlighter_opts:
        # Rouge Options › https://github.com/jneen/rouge#full-options
        css_class: 'highlight'
        #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
        span:
          line_numbers: false
        block:
          line_numbers: true
          start_line: 1

disqus:
    shortname: "guhehehe-github-io"
    url: "https://guhehehe.github.io"
    identifier: 1

nav:
  - name: "About"
    href: "/about"

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "He Gu"
      comments: true

gems:
  - jekyll-seo-tag
